### ISSUE TITLE
py 3.10 bug 

### ISSUE THREAD

**Issue by gudaocode** [jkbrzt/podcats#25]
Traceback (most recent call last):
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\Scripts\podcats.exe\__main__.py", line 7, in <module>
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\lib\site-packages\podcats\__init__.py", line 283, in main
    text_to_xml(channel.as_xml() , xmlpath)
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\lib\site-packages\podcats\__init__.py", line 230, in as_xml
    items=u''.join(episode.as_xml() for episode in sorted(self))
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\lib\site-packages\podcats\__init__.py", line 69, in __lt__
    return self.date < other.date
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\lib\site-packages\podcats\__init__.py", line 146, in date
    dt = self.get_tag('date')
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python310\lib\site-packages\podcats\__init__.py", line 112, in get_tag
    return self.tags[name][0]
TypeError: 'NoneType' object is not subscriptable

**Comment by pokulo** [comment]
This has likely be fixed in PR #29 with commit 1cc3e04caf2746276b263506d478cb18d0bd418e by ensuring `self.tags` is always a dict. Not related to the python version. `mutagen` can apparently also return `None` instead of a dict.

**Comment by pokulo** [comment]
I think, this issue can be closed unless @gudaocode opposes.

**Comment by gudaocode** [comment]
Thank you for the reply! Please close the issue。
